name: Debug AWS Credentials

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Environment
        run: |
          echo "GitHub Repository: ${{ github.repository }}"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo "GitHub Workflow: ${{ github.workflow }}"
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "GitHub Event Path: ${{ github.event_path }}"
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "GitHub Action: ${{ github.action }}"
          echo "GitHub Action Path: ${{ github.action_path }}"
          echo "GitHub Action Repository: ${{ github.action_repository }}"
          echo "GitHub Action Ref: ${{ github.action_ref }}"
          echo "GitHub API URL: ${{ github.api_url }}"
          echo "GitHub Server URL: ${{ github.server_url }}"
          echo "GitHub Run ID: ${{ github.run_id }}"
          echo "GitHub Run Number: ${{ github.run_number }}"
          echo "GitHub Run Attempt: ${{ github.run_attempt }}"
          echo "GitHub Job: ${{ github.job }}"
          echo "GitHub Actions: ${{ github.actions }}"
          echo "GitHub Token: ***" # Don't print the actual token

      - name: Debug Variables
        run: |
          echo "TERRAFORM_AWS_ASSUME_ROLE: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE || 'Not set' }}"
          echo "S3_INTEGRATION_BUCKET: ${{ vars.S3_INTEGRATION_BUCKET || 'Not set' }}"
          echo "TERRAFORM_AWS_ASSUME_ROLE_ITAR: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE_ITAR || 'Not set' }}"
          echo "S3_INTEGRATION_BUCKET_ITAR: ${{ vars.S3_INTEGRATION_BUCKET_ITAR || 'Not set' }}"
          echo "TERRAFORM_AWS_ASSUME_ROLE_CN: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE_CN || 'Not set' }}"
          echo "S3_INTEGRATION_BUCKET_CN: ${{ vars.S3_INTEGRATION_BUCKET_CN || 'Not set' }}"

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        continue-on-error: true
        with:
          role-to-assume: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2
          output-credentials: true
          debug-logging: true

      - name: Check AWS Credentials Status
        run: |
          if [ "${{ steps.aws-credentials.outcome }}" == "success" ]; then
            echo "AWS credentials configuration succeeded"
          else
            echo "AWS credentials configuration failed"
            echo "Error: ${{ steps.aws-credentials.outputs.error-message || 'No error message available' }}"
          fi

      - name: Test AWS CLI
        if: steps.aws-credentials.outcome == 'success'
        run: |
          echo "Testing AWS CLI commands..."
          echo "Getting caller identity..."
          aws sts get-caller-identity
          
          echo "Listing S3 buckets..."
          aws s3 ls
          
          if [ -n "${{ vars.S3_INTEGRATION_BUCKET }}" ]; then
            echo "Listing S3 integration bucket..."
            aws s3 ls s3://${{ vars.S3_INTEGRATION_BUCKET }}
          fi

      - name: Test OIDC Provider
        if: steps.aws-credentials.outcome != 'success'
        run: |
          echo "Testing OIDC provider configuration..."
          echo "GitHub OIDC token issuer: https://token.actions.githubusercontent.com"
          echo "GitHub OIDC token audience: sts.amazonaws.com"
          echo "GitHub OIDC token subject: repo:${{ github.repository }}:${{ github.ref }}"
          echo "GitHub OIDC token subject claim: repo:${{ github.repository }}:ref:${{ github.ref }}"
          
          echo "Please verify that your IAM role trust policy includes:"
          echo "- OIDC provider: arn:aws:iam::924305315339:oidc-provider/token.actions.githubusercontent.com"
          echo "- Condition: StringLike: token.actions.githubusercontent.com:sub: repo:${{ github.repository }}:*"

      - name: Debug IAM Role
        if: steps.aws-credentials.outcome != 'success'
        run: |
          echo "Debugging IAM role..."
          echo "Role ARN: ${{ vars.TERRAFORM_AWS_ASSUME_ROLE || 'Not set' }}"
          
          if [ -n "${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}" ]; then
            echo "Role ARN format check:"
            if [[ "${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}" =~ ^arn:aws:iam::[0-9]{12}:role/[a-zA-Z0-9+=,.@_-]+$ ]]; then
              echo "Role ARN format appears valid"
            else
              echo "Role ARN format appears invalid"
            fi
            
            echo "Role ARN components:"
            ACCOUNT_ID=$(echo "${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}" | sed -n 's/^arn:aws:iam::([0-9]{12}):role\/.*$/\1/p')
            ROLE_NAME=$(echo "${{ vars.TERRAFORM_AWS_ASSUME_ROLE }}" | sed -n 's/^arn:aws:iam::[0-9]{12}:role\/(.*)$/\1/p')
            echo "Account ID: $ACCOUNT_ID"
            echo "Role Name: $ROLE_NAME"
          fi
